Parchive/par2cmdline

par2.1

related debian bug is https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=782980

man page: add missing argument for the block-count option

---

par2repairer.cpp

The previous fix for issue #49 (Scanning extra files messes up verification) was supposed to ignore an extra file that is identical with the target file during the recovery process. But that fix caused the first extra file with a target file name (without path) matching a substring in the full path of the extra file name to be ignored during recovery attempts (issue #53). This fix discards the extra file only if the  'canonical' target path is identical with the 'canonical' extra file path. Notice that the return value of 'ExtraFile::FileName()' is already a canonical full path (see initialization of extra file list). Because all file names in the list of extra files are unique the search for a matching file name can be aborted after the first match.

Fix issue #53 / Correct fix for issue #49

---

par2creator.cpp

If the complete path to the vol*.par2-files exeeds 300 bytes, the path
is silently truncated.
Use `_MAX_PATH` define for proper buffer size.
Signed-off-by: Philipp Zimmer <pz@ggdns.de>

par2creator: use proper buffer size for volume file name generation

---

tests/test20

The build process hangs for a long time while test 20 reads from /dev/random. On my desktop it eventually completed without error after more than half an hour, on a virtualbox vm it takes even longer. Using /dev/urandom instead prevents this delay.

Use /dev/urandom in test 20

---

diskfile.cpp

PATH_MAX isn't defined on hurd, causing par2cmdline to fail to build [1]. Proposed code change works around that by trying get_current_dir_name() instead on such platforms.
[1] see https://buildd.debian.org/status/fetch.php?pkg=par2cmdline&arch=hurd-i386&ver=0.6.14-1&stamp=1439287555

Avoid unconditional use of PATH_MAX

---

par2cmdline.h
reedsolomon.cpp

- properly define __BYTE_ORDER
- remove double line, which defines __LITTLE_ENDIAN
- on gcc 4.9.3 mute c++ warning: suggest parentheses around arithmetic in operand of '|' [-Wparentheses]

Fix issue #55, on OpenBSD 5.6+ __BYTE_ORDER is not defined

---

tests/test12
tests/test13
tests/test15
tests/test18
tests/test20

- option -c to head(1) is not supported, use dd(1) instead
- option iflag to dd(1) is not supported, just drop it
- remove stray blank line
All regress tests pass on OpenBSD/amd64 5.8-current from Oct 2, 2015

OpenBSD fixes for regress scripts

---

tests/test1
tests/test10
tests/test11
tests/test12
tests/test13
tests/test14
tests/test15
tests/test16
tests/test17
tests/test2
tests/test3
tests/test4
tests/test5
tests/test6
tests/test7
tests/test8
tests/test9
tests/testMem

Not all tar implementations, will handle gzip'ed archives
automatically. This for example helps on OpenBSD.

Explicitly add -z option to tar(1) during extraction.

---

README
README.md
commandline.cpp
par2.1
tests/test19

By default there is no skipping of data enabled now to avoid a possible
DOS where we get md5 collisions in a parchive. When you think there is
such a case you must now explicitly pass -N to skip blocks.
implements #65
Signed-off-by: BlackEagle <ike.devolder@gmail.com>

invert -N behaviour, -N now enables skipping

---

par2.1

An older par2 manpage written for debian, in use before the current manpage supplied with par2cmdline's own releases, contained an section showcasing usage examples of the program. Recently, the return of this examples section was requested a debian bug report [1].
Although the referenced hardware specs aren't exactly high end these days, the info in itself seems correct and could surely prove useful for end users.
1: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=827720

add examples section from the old debian manpage

---

build/build-win32.sh
build/build-win64.sh

Signed-off-by: BlackEagle <ike.devolder@gmail.com>

build-win* use -s flag for gcc then we don't need strip anymore, #94

---

src/diskfile.cpp

The aliasing waring was given for similar constructs of
((LONG*)&filesize)[0] and ((LONG*)_offset)[0]. The update introduced in
1713190de7af346c29496a080815835071d3b17f copy pasted the filesize fix to
the _offset areas, so the values used there were wrong, introducing an
800 byte offset in all par2 files and completely corrupt par2 content
when creating new parfiles on windows.
Bug-introduced: 1713190de7af346c29496a080815835071d3b17f
Fixes: #109
Signed-off-by: BlackEagle <ike.devolder@gmail.com>

copy pasted to much in aliasing fix

---

src/diskfile.cpp
src/diskfile.h
src/diskfile_test.cpp

Currently, when a blocksize is greater than 4GB, a call to DiskFile::Read() or DiskFile::Write() fails.  This commit changes it, so that larger reads are broken into smaller ones.  This is necessary on Windows, which limits its calls to <4GB.
The change on Unix is less necessary.  The C library can break up large reads and writes into smaller OS calls on its own.  It would be weird to have a limit of 32-bit reads on a 64-bit filesystem.  But maybe it happens in Cygwin?

Support file I/O on blocksize greater than 4GB

---

src/diskfile.cpp

The original call to stat() failed on WIN32 for large (> 2GB) files.  I moved DiskFile::FileExists() into the WIN32/Unix sections next to GetFileSize() so that Unix builds would still get the stat() version.
Having FileExists() and GetFileSize() adjacent is also useful because GetFileSize() has the same stat/_stati64 difference between WIN32/Unix.

Used _stati64() for WIN32 DiskFile::FileExists()

---

src/reedsolomon_test.cpp

I changed the test to explicitly write a little-endian 1 value into the arrays.  It also converts from little-endian to native-endian when reading out of the array.
See issue #143

Fix for Github issue #143.  Test did not account for endianness correctly.

---

src/descriptionpacket.cpp

A `string::at` call on `pos` `1` could be called on a string that is one
character long, so it throws an `out_of_range` and core dumps.  Avoid
this by checking the string size beforehand.
Test: `echo abc >/tmp/f && par2 c /tmp/f`
Close: #145

fix: allow single char filename

---

Makefile.am
src/commandline.cpp
tests/test28

Enforce that the `-qq` silent noise level is truly silent (i.e. gives no
output).  Fix it for `create`.  Add a test `test28` to ensure it for
`create`, `verify`, and `repair`.

fix: enforce -qq silent

---

Makefile.am

This is useful when installing into a staging directory to avoid getting links
temporarily pointing out of that directory.

Install relative symlinks instead of absolute ones

---

src/filechecksummer.cpp
src/filechecksummer.h

The current FileChecksummer almost always [performs a memory copy](https://github.com/Parchive/par2cmdline/blob/0b266b5d41669fc1977f327c5d7e422b1ef06ac8/src/filechecksummer.cpp#L112-L116) once a read has occurred. This is because it fills the entire buffer, and every `Jump` call can, at most, consume half that buffer, leading to `keep` being greater than 0 in all cases except reaching the end-of-file.
This seemingly unnecessary copying around of memory seems rather wasteful.  
A solution may be to turn the buffer into some sort of circular buffer, however implementing such is rather complex/fiddly.
With the goal of simplicity, I've implemented a much easier approach that yields most of the benefit - instead of filling the buffer completely, only fill it half way, most of the time. Since …

Avoid copying back memory in FileChecksummer when data is valid

---

src/diskfile.cpp

I updated diskfile.cpp to fix the bug, which I posted at [issues #169](https://github.com/Parchive/par2cmdline/issues/169) ago. 
The bug was reported at [issues #173](https://github.com/Parchive/par2cmdline/issues/173), too.

enable Recurse flag on Windows OS

---

src/commandline.cpp
src/libpar2internal.h
src/par2creator.cpp
src/par2repairer.cpp

I think I have cherry-picked the relevant commits for there from https://github.com/animetosho/par2cmdline-turbo

Updates from turbo

---

Makefile.am
src/commandline.cpp
src/commandline_test.cpp
tests/test32

Cause: default the par2 volumes creation is variable, so the number of blocks in the recovery files is exponentially increased, if you request too many files the needed recovery blocks can't fill the requested number of files.

When number of recovery files is set, you get "File already exists"

---

src/diskfile.cpp

This will give us the info of the file we are pointing to instead of giving the info a potential symlink is pointing to. This will effectively also only include actual files in the recovery and not refer to symlinks and such.
Tickets: #164
Closes: #164

diskfile, replace stat use with lstat

---

.github/workflows/build-release.yml

This adds a Linux armhf/armv7 build for 32-bit ARM platforms.
( Requested from https://github.com/animetosho/par2cmdline-turbo/issues/43 )

Add armhf Linux build
